// Static activity dataset for Actify.
// Used as the fallback when the recommendation engine has no API-backed
// suggestions to draw from. Exposed on window.GENERIC_ACTIVITIES.
//
// Fields:
//   id              unique kebab-case slug
//   title           human-readable name
//   category        Create | Social | Relax | GoOut
//   minutes         typical duration (10-120)
//   moodTags        moods this activity fits well
//   excludedMoods   moods this activity must never be shown for
//   tags            interest tags this activity matches (lowercase; engine
//                   should compare against user interests case-insensitively)

window.GENERIC_ACTIVITIES = [
  // ---------------- Create ----------------
  {
    id: "draw-something",
    title: "Draw something",
    category: "Create",
    minutes: 30,
    moodTags: ["create", "relax"],
    excludedMoods: [],
    tags: ["art"],
  },
  {
    id: "write-in-journal",
    title: "Write in a journal",
    category: "Create",
    minutes: 15,
    moodTags: ["create", "relax", "learn"],
    excludedMoods: ["social", "energetic"],
    tags: ["reading"],
  },
  {
    id: "learn-guitar-chords",
    title: "Learn 3 chords on guitar",
    category: "Create",
    minutes: 45,
    moodTags: ["create", "learn"],
    excludedMoods: ["social"],
    tags: ["music"],
  },
  {
    id: "try-new-recipe",
    title: "Try a new recipe",
    category: "Create",
    minutes: 90,
    moodTags: ["create", "fun", "learn"],
    excludedMoods: [],
    tags: ["food"],
  },
  {
    id: "edit-phone-photos",
    title: "Edit photos from your phone",
    category: "Create",
    minutes: 30,
    moodTags: ["create", "relax"],
    excludedMoods: ["social", "energetic"],
    tags: ["art"],
  },
  {
    id: "write-short-story",
    title: "Write a short story",
    category: "Create",
    minutes: 60,
    moodTags: ["create", "learn"],
    excludedMoods: ["social", "energetic"],
    tags: ["reading"],
  },
  {
    id: "build-side-project",
    title: "Build a small side project",
    category: "Create",
    minutes: 120,
    moodTags: ["create", "learn", "energetic"],
    excludedMoods: ["social", "relax"],
    tags: ["coding"],
  },
  {
    id: "make-friend-playlist",
    title: "Make a playlist for a friend",
    category: "Create",
    minutes: 20,
    moodTags: ["create", "social", "fun"],
    excludedMoods: ["energetic"],
    tags: ["music", "friends"],
  },
  {
    id: "sketch-comic-strip",
    title: "Sketch a comic strip",
    category: "Create",
    minutes: 45,
    moodTags: ["create", "fun"],
    excludedMoods: ["social"],
    tags: ["art"],
  },

  // ---------------- Social ----------------
  {
    id: "call-old-friend",
    title: "Call a friend you haven't talked to in a while",
    category: "Social",
    minutes: 30,
    moodTags: ["social", "fun"],
    excludedMoods: ["energetic"],
    tags: ["friends"],
  },
  {
    id: "video-call-family",
    title: "Video call family",
    category: "Social",
    minutes: 45,
    moodTags: ["social"],
    excludedMoods: ["energetic", "bored"],
    tags: ["family"],
  },
  {
    id: "plan-hangout",
    title: "Plan a hangout",
    category: "Social",
    minutes: 20,
    moodTags: ["social", "fun", "learn"],
    excludedMoods: ["energetic", "bored"],
    tags: ["friends", "exploring"],
  },
  {
    id: "text-appreciation",
    title: "Text someone you appreciate",
    category: "Social",
    minutes: 10,
    moodTags: ["social", "relax"],
    excludedMoods: ["energetic"],
    tags: ["friends", "family"],
  },
  {
    id: "host-game-night",
    title: "Host a game night",
    category: "Social",
    minutes: 120,
    moodTags: ["social", "fun", "energetic"],
    excludedMoods: ["relax"],
    tags: ["gaming", "friends"],
  },
  {
    id: "cook-with-someone",
    title: "Cook dinner with someone",
    category: "Social",
    minutes: 90,
    moodTags: ["social", "fun", "create"],
    excludedMoods: ["energetic"],
    tags: ["food", "friends"],
  },
  {
    id: "ask-parent-childhood",
    title: "Ask a parent about their childhood",
    category: "Social",
    minutes: 45,
    moodTags: ["social", "learn"],
    excludedMoods: ["energetic"],
    tags: ["family"],
  },
  {
    id: "send-postcard",
    title: "Send a postcard",
    category: "Social",
    minutes: 20,
    moodTags: ["social", "create", "relax"],
    excludedMoods: ["energetic"],
    tags: ["friends", "family"],
  },
  {
    id: "catch-up-coffee",
    title: "Catch up over coffee",
    category: "Social",
    minutes: 60,
    moodTags: ["social", "relax", "fun"],
    excludedMoods: ["energetic"],
    tags: ["friends", "food"],
  },

  // ---------------- Relax ----------------
  {
    id: "walk-no-destination",
    title: "Take a walk with no destination",
    category: "Relax",
    minutes: 30,
    moodTags: ["relax", "energetic"],
    excludedMoods: ["social"],
    tags: ["exploring", "fitness"],
  },
  {
    id: "listen-full-album",
    title: "Listen to a full album",
    category: "Relax",
    minutes: 45,
    moodTags: ["relax", "fun"],
    excludedMoods: ["social", "energetic"],
    tags: ["music"],
  },
  {
    id: "stretch-routine",
    title: "Do a 10-minute stretch routine",
    category: "Relax",
    minutes: 10,
    moodTags: ["relax", "energetic", "learn"],
    excludedMoods: ["social"],
    tags: ["fitness"],
  },
  {
    id: "take-nap",
    title: "Take a nap",
    category: "Relax",
    minutes: 30,
    moodTags: ["relax"],
    excludedMoods: ["energetic", "social", "fun", "create", "learn", "bored"],
    tags: [],
  },
  {
    id: "read-chapter",
    title: "Read a chapter of a book",
    category: "Relax",
    minutes: 30,
    moodTags: ["relax", "learn"],
    excludedMoods: ["social", "energetic"],
    tags: ["reading"],
  },
  {
    id: "comfort-movie",
    title: "Watch a comfort movie",
    category: "Relax",
    minutes: 120,
    moodTags: ["relax", "fun"],
    excludedMoods: ["social", "energetic", "bored"],
    tags: ["movies"],
  },
  {
    id: "brew-tea",
    title: "Brew tea and sit with it",
    category: "Relax",
    minutes: 15,
    moodTags: ["relax"],
    excludedMoods: ["social", "energetic", "create", "learn", "bored"],
    tags: [],
  },
  {
    id: "tidy-small-space",
    title: "Tidy one small space",
    category: "Relax",
    minutes: 20,
    moodTags: ["relax", "create"],
    excludedMoods: ["social", "energetic", "bored"],
    tags: [],
  },
  {
    id: "face-mask-podcast",
    title: "Do a face mask while listening to a podcast",
    category: "Relax",
    minutes: 30,
    moodTags: ["relax", "fun"],
    excludedMoods: ["social", "energetic"],
    tags: [],
  },

  // ---------------- GoOut ----------------
  {
    id: "coffee-somewhere-new",
    title: "Grab coffee somewhere new",
    category: "GoOut",
    minutes: 45,
    moodTags: ["fun", "social", "surprise"],
    excludedMoods: ["relax"],
    tags: ["food", "exploring"],
  },
  {
    id: "go-to-park",
    title: "Go to a park",
    category: "GoOut",
    minutes: 60,
    moodTags: ["relax", "energetic"],
    excludedMoods: ["social"],
    tags: ["exploring", "fitness"],
  },
  {
    id: "window-shop",
    title: "Window shop downtown",
    category: "GoOut",
    minutes: 45,
    moodTags: ["fun", "relax", "surprise"],
    excludedMoods: ["social", "bored"],
    tags: ["exploring"],
  },
  {
    id: "new-restaurant",
    title: "Try a restaurant you haven't been to",
    category: "GoOut",
    minutes: 90,
    moodTags: ["fun", "surprise", "social"],
    excludedMoods: ["relax"],
    tags: ["food", "exploring"],
  },
  {
    id: "visit-museum",
    title: "Visit a museum",
    category: "GoOut",
    minutes: 120,
    moodTags: ["learn", "fun", "surprise"],
    excludedMoods: ["social", "bored"],
    tags: ["exploring", "art"],
  },
  {
    id: "browse-bookstore",
    title: "Browse a bookstore",
    category: "GoOut",
    minutes: 60,
    moodTags: ["relax", "learn", "fun"],
    excludedMoods: ["social", "energetic"],
    tags: ["reading", "exploring"],
  },
  {
    id: "take-hike",
    title: "Take a hike",
    category: "GoOut",
    minutes: 120,
    moodTags: ["energetic", "learn", "surprise"],
    excludedMoods: ["relax", "social"],
    tags: ["fitness", "exploring"],
  },
  {
    id: "farmers-market",
    title: "Go to a farmers market",
    category: "GoOut",
    minutes: 60,
    moodTags: ["fun", "learn", "social"],
    excludedMoods: ["relax"],
    tags: ["food", "exploring"],
  },
  {
    id: "new-neighborhood",
    title: "Walk a new neighborhood",
    category: "GoOut",
    minutes: 90,
    moodTags: ["energetic", "surprise", "fun"],
    excludedMoods: ["relax", "social"],
    tags: ["exploring", "fitness"],
  },
];
