// Static activity dataset for Actify.
// Used as the fallback when the recommendation engine has no API-backed
// suggestions to draw from. Exposed on window.GENERIC_ACTIVITIES.
//
// Fields:
//   id              unique kebab-case slug
//   title           human-readable name
//   category        Create | Social | Relax | GoOut | Watch | Play | Read
//   minutes         typical duration (10-120); null = flexible/open-ended
//   moodTags        moods this activity fits well (used in scoring bonus)
//   excludedMoods   moods this activity must never be shown for
//   tags            interest tags this activity matches (lowercase)

window.GENERIC_ACTIVITIES = [
  // ═══════════════════ Create ═══════════════════
  {
    id: 'draw-something',
    title: 'Draw something',
    category: 'Create',
    minutes: 30,
    moodTags: ['create', 'relax'],
    excludedMoods: [],
    tags: ['art'],
  },
  {
    id: 'write-in-journal',
    title: 'Write in a journal',
    category: 'Create',
    minutes: 15,
    moodTags: ['create', 'relax', 'learn'],
    excludedMoods: ['social', 'energetic'],
    tags: ['reading'],
  },
  {
    id: 'learn-guitar-chords',
    title: 'Learn 3 chords on guitar',
    category: 'Create',
    minutes: 45,
    moodTags: ['create', 'learn'],
    excludedMoods: ['social'],
    tags: ['music'],
  },
  {
    id: 'try-new-recipe',
    title: 'Try a new recipe',
    category: 'Create',
    minutes: 90,
    moodTags: ['create', 'fun', 'learn'],
    excludedMoods: [],
    tags: ['food'],
  },
  {
    id: 'edit-phone-photos',
    title: 'Edit photos from your phone',
    category: 'Create',
    minutes: 30,
    moodTags: ['create', 'relax'],
    excludedMoods: ['social', 'energetic'],
    tags: ['art'],
  },
  {
    id: 'write-short-story',
    title: 'Write a short story',
    category: 'Create',
    minutes: 60,
    moodTags: ['create', 'learn'],
    excludedMoods: ['social', 'energetic'],
    tags: ['reading'],
  },
  {
    id: 'build-side-project',
    title: 'Build a small side project',
    category: 'Create',
    minutes: 120,
    moodTags: ['create', 'learn', 'energetic'],
    excludedMoods: ['social', 'relax'],
    tags: ['coding'],
  },
  {
    id: 'make-friend-playlist',
    title: 'Make a playlist for a friend',
    category: 'Create',
    minutes: 20,
    moodTags: ['create', 'social', 'fun'],
    excludedMoods: ['energetic'],
    tags: ['music', 'friends'],
  },
  {
    id: 'sketch-comic-strip',
    title: 'Sketch a comic strip',
    category: 'Create',
    minutes: 45,
    moodTags: ['create', 'fun'],
    excludedMoods: ['social'],
    tags: ['art'],
  },
  {
    id: 'make-digital-art',
    title: 'Make some digital art or a doodle',
    category: 'Create',
    minutes: 30,
    moodTags: ['create', 'bored', 'relax'],
    excludedMoods: ['energetic'],
    tags: ['art'],
  },
  {
    id: 'write-poem',
    title: 'Write a poem about your day',
    category: 'Create',
    minutes: 20,
    moodTags: ['create', 'relax', 'surprise'],
    excludedMoods: ['energetic', 'social'],
    tags: ['reading'],
  },
  {
    id: 'design-room-layout',
    title: 'Redesign your room layout on paper',
    category: 'Create',
    minutes: 30,
    moodTags: ['create', 'bored', 'learn'],
    excludedMoods: ['social'],
    tags: ['art'],
  },

  // ═══════════════════ Social ═══════════════════
  {
    id: 'call-old-friend',
    title: 'Call a friend you haven\'t talked to in a while',
    category: 'Social',
    minutes: 30,
    moodTags: ['social', 'fun'],
    excludedMoods: ['energetic'],
    tags: ['friends'],
  },
  {
    id: 'video-call-family',
    title: 'Video call family',
    category: 'Social',
    minutes: 45,
    moodTags: ['social'],
    excludedMoods: ['energetic', 'bored'],
    tags: ['family'],
  },
  {
    id: 'plan-hangout',
    title: 'Plan a hangout',
    category: 'Social',
    minutes: 20,
    moodTags: ['social', 'fun', 'learn'],
    excludedMoods: ['energetic', 'bored'],
    tags: ['friends', 'exploring'],
  },
  {
    id: 'text-appreciation',
    title: 'Text someone you appreciate',
    category: 'Social',
    minutes: 10,
    moodTags: ['social', 'relax'],
    excludedMoods: ['energetic'],
    tags: ['friends', 'family'],
  },
  {
    id: 'host-game-night',
    title: 'Host a game night',
    category: 'Social',
    minutes: 120,
    moodTags: ['social', 'fun', 'energetic'],
    excludedMoods: ['relax'],
    tags: ['gaming', 'friends'],
  },
  {
    id: 'cook-with-someone',
    title: 'Cook dinner with someone',
    category: 'Social',
    minutes: 90,
    moodTags: ['social', 'fun', 'create'],
    excludedMoods: ['energetic'],
    tags: ['food', 'friends'],
  },
  {
    id: 'ask-parent-childhood',
    title: 'Ask a parent about their childhood',
    category: 'Social',
    minutes: 45,
    moodTags: ['social', 'learn'],
    excludedMoods: ['energetic'],
    tags: ['family'],
  },
  {
    id: 'send-postcard',
    title: 'Send a postcard',
    category: 'Social',
    minutes: 20,
    moodTags: ['social', 'create', 'relax'],
    excludedMoods: ['energetic'],
    tags: ['friends', 'family'],
  },
  {
    id: 'catch-up-coffee',
    title: 'Catch up over coffee',
    category: 'Social',
    minutes: 60,
    moodTags: ['social', 'relax', 'fun'],
    excludedMoods: ['energetic'],
    tags: ['friends', 'food'],
  },
  {
    id: 'write-letter-friend',
    title: 'Write a handwritten letter to a friend',
    category: 'Social',
    minutes: 20,
    moodTags: ['social', 'create', 'relax'],
    excludedMoods: ['energetic', 'bored'],
    tags: ['friends'],
  },
  {
    id: 'share-playlist-friend',
    title: 'Send someone a playlist that reminds you of them',
    category: 'Social',
    minutes: 15,
    moodTags: ['social', 'fun', 'surprise'],
    excludedMoods: [],
    tags: ['music', 'friends'],
  },

  // ═══════════════════ Relax ═══════════════════
  {
    id: 'walk-no-destination',
    title: 'Take a walk with no destination',
    category: 'Relax',
    minutes: 30,
    moodTags: ['relax', 'energetic', 'bored'],
    excludedMoods: ['social'],
    tags: ['exploring', 'fitness'],
  },
  {
    id: 'listen-full-album',
    title: 'Listen to a full album',
    category: 'Relax',
    minutes: 45,
    moodTags: ['relax', 'fun', 'bored'],
    excludedMoods: ['social', 'energetic'],
    tags: ['music'],
  },
  {
    id: 'stretch-routine',
    title: 'Do a 10-minute stretch routine',
    category: 'Relax',
    minutes: 10,
    moodTags: ['relax', 'energetic', 'learn'],
    excludedMoods: ['social'],
    tags: ['fitness'],
  },
  {
    id: 'take-nap',
    title: 'Take a nap',
    category: 'Relax',
    minutes: 30,
    moodTags: ['relax'],
    excludedMoods: ['energetic', 'social', 'fun', 'create', 'learn', 'bored'],
    tags: [],
  },
  {
    id: 'read-chapter',
    title: 'Read a chapter of a book',
    category: 'Relax',
    minutes: 30,
    moodTags: ['relax', 'learn'],
    excludedMoods: ['social', 'energetic'],
    tags: ['reading'],
  },
  {
    id: 'comfort-movie',
    title: 'Watch a comfort movie',
    category: 'Relax',
    minutes: 120,
    moodTags: ['relax', 'fun'],
    excludedMoods: ['social', 'energetic', 'bored'],
    tags: ['movies'],
  },
  {
    id: 'brew-tea',
    title: 'Brew tea and sit with it',
    category: 'Relax',
    minutes: 15,
    moodTags: ['relax'],
    excludedMoods: ['social', 'energetic', 'create', 'learn', 'bored'],
    tags: [],
  },
  {
    id: 'tidy-small-space',
    title: 'Tidy one small space',
    category: 'Relax',
    minutes: 20,
    moodTags: ['relax', 'create'],
    excludedMoods: ['social', 'energetic', 'bored'],
    tags: [],
  },
  {
    id: 'face-mask-podcast',
    title: 'Do a face mask while listening to a podcast',
    category: 'Relax',
    minutes: 30,
    moodTags: ['relax', 'fun'],
    excludedMoods: ['social', 'energetic'],
    tags: [],
  },
  {
    id: 'sit-outside',
    title: 'Sit outside and watch the sky for 10 minutes',
    category: 'Relax',
    minutes: 10,
    moodTags: ['relax', 'bored', 'surprise'],
    excludedMoods: ['energetic', 'social'],
    tags: [],
  },
  {
    id: 'guided-meditation',
    title: 'Try a guided meditation',
    category: 'Relax',
    minutes: 15,
    moodTags: ['relax', 'learn'],
    excludedMoods: ['energetic', 'social', 'fun'],
    tags: ['fitness'],
  },
  {
    id: 'playlist-discover',
    title: 'Let a discovery playlist surprise you',
    category: 'Relax',
    minutes: 30,
    moodTags: ['relax', 'bored', 'surprise'],
    excludedMoods: ['energetic'],
    tags: ['music'],
  },

  // ═══════════════════ GoOut ═══════════════════
  {
    id: 'coffee-somewhere-new',
    title: 'Grab coffee somewhere new',
    category: 'GoOut',
    minutes: 45,
    moodTags: ['fun', 'social', 'surprise', 'bored'],
    excludedMoods: ['relax'],
    tags: ['food', 'exploring'],
  },
  {
    id: 'go-to-park',
    title: 'Go to a park',
    category: 'GoOut',
    minutes: 60,
    moodTags: ['relax', 'energetic', 'bored'],
    excludedMoods: ['social'],
    tags: ['exploring', 'fitness'],
  },
  {
    id: 'window-shop',
    title: 'Window shop downtown',
    category: 'GoOut',
    minutes: 45,
    moodTags: ['fun', 'relax', 'surprise'],
    excludedMoods: ['social', 'bored'],
    tags: ['exploring'],
  },
  {
    id: 'new-restaurant',
    title: 'Try a restaurant you haven\'t been to',
    category: 'GoOut',
    minutes: 90,
    moodTags: ['fun', 'surprise', 'social'],
    excludedMoods: ['relax'],
    tags: ['food', 'exploring'],
  },
  {
    id: 'visit-museum',
    title: 'Visit a museum',
    category: 'GoOut',
    minutes: 120,
    moodTags: ['learn', 'fun', 'surprise'],
    excludedMoods: ['social', 'bored'],
    tags: ['exploring', 'art'],
  },
  {
    id: 'browse-bookstore',
    title: 'Browse a bookstore',
    category: 'GoOut',
    minutes: 60,
    moodTags: ['relax', 'learn', 'fun'],
    excludedMoods: ['social', 'energetic'],
    tags: ['reading', 'exploring'],
  },
  {
    id: 'take-hike',
    title: 'Take a hike',
    category: 'GoOut',
    minutes: 120,
    moodTags: ['energetic', 'learn', 'surprise'],
    excludedMoods: ['relax', 'social'],
    tags: ['fitness', 'exploring'],
  },
  {
    id: 'farmers-market',
    title: 'Go to a farmers market',
    category: 'GoOut',
    minutes: 60,
    moodTags: ['fun', 'learn', 'social'],
    excludedMoods: ['relax'],
    tags: ['food', 'exploring'],
  },
  {
    id: 'new-neighborhood',
    title: 'Walk a new neighborhood',
    category: 'GoOut',
    minutes: 90,
    moodTags: ['energetic', 'surprise', 'fun'],
    excludedMoods: ['relax', 'social'],
    tags: ['exploring', 'fitness'],
  },
  {
    id: 'sunrise-walk',
    title: 'Take an early sunrise walk',
    category: 'GoOut',
    minutes: 30,
    moodTags: ['energetic', 'relax', 'surprise'],
    excludedMoods: ['social'],
    tags: ['fitness', 'exploring'],
  },
  {
    id: 'street-art-hunt',
    title: 'Go on a street art hunt in your city',
    category: 'GoOut',
    minutes: 60,
    moodTags: ['fun', 'surprise', 'create', 'bored'],
    excludedMoods: ['relax'],
    tags: ['art', 'exploring'],
  },
  {
    id: 'library-visit',
    title: 'Visit your local library',
    category: 'GoOut',
    minutes: 45,
    moodTags: ['learn', 'relax', 'bored'],
    excludedMoods: ['energetic', 'social'],
    tags: ['reading', 'exploring'],
  },

  // ═══════════════════ Watch ═══════════════════
  // Generic fallbacks when TMDB is unavailable.
  {
    id: 'watch-documentary',
    title: 'Watch a documentary',
    category: 'Watch',
    minutes: 90,
    moodTags: ['learn', 'relax', 'bored'],
    excludedMoods: ['energetic', 'social'],
    tags: ['movies'],
  },
  {
    id: 'watch-comedy-special',
    title: 'Watch a stand-up comedy special',
    category: 'Watch',
    minutes: 60,
    moodTags: ['fun', 'relax', 'bored'],
    excludedMoods: ['energetic'],
    tags: ['movies'],
  },
  {
    id: 'watch-short-film',
    title: 'Watch a short film (under 30 min)',
    category: 'Watch',
    minutes: 30,
    moodTags: ['relax', 'fun', 'bored', 'surprise'],
    excludedMoods: ['energetic'],
    tags: ['movies'],
  },
  {
    id: 'watch-mini-series-ep',
    title: 'Watch one episode of a new mini-series',
    category: 'Watch',
    minutes: 45,
    moodTags: ['relax', 'bored', 'fun'],
    excludedMoods: ['energetic', 'social'],
    tags: ['movies'],
  },
  {
    id: 'watch-travel-vlog',
    title: 'Watch a travel vlog somewhere you\'d love to go',
    category: 'Watch',
    minutes: 20,
    moodTags: ['relax', 'surprise', 'fun', 'bored'],
    excludedMoods: ['energetic'],
    tags: ['movies', 'exploring'],
  },

  // ═══════════════════ Play ═══════════════════
  // Generic fallbacks when RAWG is unavailable.
  {
    id: 'play-puzzle-game',
    title: 'Play a quick puzzle game',
    category: 'Play',
    minutes: 20,
    moodTags: ['learn', 'relax', 'bored'],
    excludedMoods: ['social', 'energetic'],
    tags: ['gaming'],
  },
  {
    id: 'play-board-game-solo',
    title: 'Play a solo board game or card game',
    category: 'Play',
    minutes: 45,
    moodTags: ['fun', 'relax', 'bored'],
    excludedMoods: ['energetic'],
    tags: ['gaming'],
  },
  {
    id: 'replay-favourite-game',
    title: 'Replay a favourite game you haven\'t touched in a while',
    category: 'Play',
    minutes: null,
    moodTags: ['fun', 'relax', 'bored'],
    excludedMoods: [],
    tags: ['gaming'],
  },
  {
    id: 'try-free-game',
    title: 'Try a free browser or mobile game you\'ve never played',
    category: 'Play',
    minutes: 30,
    moodTags: ['fun', 'bored', 'surprise'],
    excludedMoods: [],
    tags: ['gaming'],
  },
  {
    id: 'play-multiplayer-friend',
    title: 'Play an online game with a friend',
    category: 'Play',
    minutes: 60,
    moodTags: ['fun', 'social', 'energetic'],
    excludedMoods: ['relax'],
    tags: ['gaming', 'friends'],
  },

  // ═══════════════════ Read ═══════════════════
  // Generic fallbacks when Open Library / Articles adapters are unavailable.
  {
    id: 'read-long-article',
    title: 'Read a long-form article or essay',
    category: 'Read',
    minutes: 20,
    moodTags: ['learn', 'relax', 'bored'],
    excludedMoods: ['energetic', 'social'],
    tags: ['reading'],
  },
  {
    id: 'read-wikipedia-rabbit-hole',
    title: 'Start a Wikipedia rabbit hole on something random',
    category: 'Read',
    minutes: 30,
    moodTags: ['learn', 'bored', 'surprise'],
    excludedMoods: ['energetic', 'social'],
    tags: ['reading'],
  },
  {
    id: 'read-graphic-novel',
    title: 'Read a graphic novel or manga chapter',
    category: 'Read',
    minutes: 30,
    moodTags: ['relax', 'fun', 'bored'],
    excludedMoods: ['social', 'energetic'],
    tags: ['reading', 'art'],
  },
  {
    id: 'read-poetry-collection',
    title: 'Read a poetry collection for 15 minutes',
    category: 'Read',
    minutes: 15,
    moodTags: ['relax', 'create', 'learn'],
    excludedMoods: ['energetic', 'social'],
    tags: ['reading'],
  },
  {
    id: 'read-book-synopsis',
    title: 'Read synopses of books you want to read and pick your next one',
    category: 'Read',
    minutes: 15,
    moodTags: ['learn', 'relax', 'bored'],
    excludedMoods: ['energetic'],
    tags: ['reading'],
  },
];
